version: "2"

networks:
  whmcs-prod:
    external: false

services:
  nginx:
    image: sagniks/nginx-whmcs-docker
    container_name: whmcs-prod_nginx
    restart: always
    ports:
        - "127.0.0.1:4222:80"
    volumes:
        - /srv/whmcs-prod/htdocs:/code
        - /srv/whmcs-prod/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - /srv/whmcs-prod/nginx/logs/whmcs-prod_access.log:/var/log/nginx/whmcs-prod_access.log
        - /srv/whmcs-prod/nginx/logs/whmcs-prod_error.log:/var/log/nginx/whmcs-prod_error.log
    depends_on:
        - php
    networks:
        - whmcs-prod

  db:
    image: mariadb:10
    container_name: whmcs-prod_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=<random_passwd>
      - MYSQL_USER=whmcs
      - MYSQL_PASSWORD=<random_passwd>
      - MYSQL_DATABASE=whmcs
    depends_on:
      - nginx
    networks:
      - whmcs-prod
    volumes:
      - /srv/whmcs-prod/mysql:/var/lib/mysql

  php:
    image: sagniks/php7.3-whmcs-docker
    container_name: whmcs-prod_php
    restart: always
    volumes:
      - /srv/whmcs-prod/htdocs:/code
      - /srv/whmcs-prod/php-fpm/php.ini:/usr/local/etc/php/php.ini       
    networks:
      - whmcs-prod
